// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://behtfcplwxpxearvkcqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaHRmY3Bsd3hweGVhcnZrY3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzU1MDIsImV4cCI6MjA2ODU1MTUwMn0.D9rVOChCPI1vYOI0xmEMQoiPQ3AqISnAUED5KF7gS0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});